export type ImageType = {
  url: string;
  extension: string;
  alternativeText: string;
  caption: string;
  createdAt: string;
  ext: string;
  formats: object;
  hash: string;
  height: number;
  id: number;
  mime: string;
  name: string;
  previewUrl: string;
  provider: string;
  provider_metadata: string;
  size: number;
  updatedAt: string;
  width: number;
};
